// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather.ext.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//请求参数
type DataReq struct {
	AppSecret            string   `protobuf:"bytes,111,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	CityCode             string   `protobuf:"bytes,112,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	City                 string   `protobuf:"bytes,113,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataReq) Reset()         { *m = DataReq{} }
func (m *DataReq) String() string { return proto.CompactTextString(m) }
func (*DataReq) ProtoMessage()    {}
func (*DataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{0}
}

func (m *DataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataReq.Unmarshal(m, b)
}
func (m *DataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataReq.Marshal(b, m, deterministic)
}
func (m *DataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataReq.Merge(m, src)
}
func (m *DataReq) XXX_Size() int {
	return xxx_messageInfo_DataReq.Size(m)
}
func (m *DataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DataReq.DiscardUnknown(m)
}

var xxx_messageInfo_DataReq proto.InternalMessageInfo

func (m *DataReq) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *DataReq) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *DataReq) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

//天气预报的数据
type ForecastData struct {
	CityCode             string         `protobuf:"bytes,1,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	City                 string         `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	UpdateTime           string         `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Data                 []*WeatherData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ForecastData) Reset()         { *m = ForecastData{} }
func (m *ForecastData) String() string { return proto.CompactTextString(m) }
func (*ForecastData) ProtoMessage()    {}
func (*ForecastData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{1}
}

func (m *ForecastData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForecastData.Unmarshal(m, b)
}
func (m *ForecastData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForecastData.Marshal(b, m, deterministic)
}
func (m *ForecastData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForecastData.Merge(m, src)
}
func (m *ForecastData) XXX_Size() int {
	return xxx_messageInfo_ForecastData.Size(m)
}
func (m *ForecastData) XXX_DiscardUnknown() {
	xxx_messageInfo_ForecastData.DiscardUnknown(m)
}

var xxx_messageInfo_ForecastData proto.InternalMessageInfo

func (m *ForecastData) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *ForecastData) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ForecastData) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *ForecastData) GetData() []*WeatherData {
	if m != nil {
		return m.Data
	}
	return nil
}

//当前天气预报的数据
type NowData struct {
	CityCode             string       `protobuf:"bytes,1,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	City                 string       `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	UpdateTime           string       `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Data                 *WeatherData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NowData) Reset()         { *m = NowData{} }
func (m *NowData) String() string { return proto.CompactTextString(m) }
func (*NowData) ProtoMessage()    {}
func (*NowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{2}
}

func (m *NowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NowData.Unmarshal(m, b)
}
func (m *NowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NowData.Marshal(b, m, deterministic)
}
func (m *NowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NowData.Merge(m, src)
}
func (m *NowData) XXX_Size() int {
	return xxx_messageInfo_NowData.Size(m)
}
func (m *NowData) XXX_DiscardUnknown() {
	xxx_messageInfo_NowData.DiscardUnknown(m)
}

var xxx_messageInfo_NowData proto.InternalMessageInfo

func (m *NowData) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *NowData) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *NowData) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *NowData) GetData() *WeatherData {
	if m != nil {
		return m.Data
	}
	return nil
}

//天气情况的数据
type WeatherData struct {
	Id                   string   `protobuf:"bytes,801,opt,name=id,proto3" json:"id,omitempty"`
	CityCode             string   `protobuf:"bytes,802,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	City                 string   `protobuf:"bytes,803,opt,name=city,proto3" json:"city,omitempty"`
	Date                 string   `protobuf:"bytes,804,opt,name=date,proto3" json:"date,omitempty"`
	UpdateTime           string   `protobuf:"bytes,805,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Tem                  string   `protobuf:"bytes,806,opt,name=tem,proto3" json:"tem,omitempty"`
	TemHigh              string   `protobuf:"bytes,807,opt,name=temHigh,proto3" json:"temHigh,omitempty"`
	TemLow               string   `protobuf:"bytes,808,opt,name=temLow,proto3" json:"temLow,omitempty"`
	CondCodeDay          string   `protobuf:"bytes,809,opt,name=condCodeDay,proto3" json:"condCodeDay,omitempty"`
	CondTxtDay           string   `protobuf:"bytes,811,opt,name=condTxtDay,proto3" json:"condTxtDay,omitempty"`
	CondCodeNight        string   `protobuf:"bytes,812,opt,name=condCodeNight,proto3" json:"condCodeNight,omitempty"`
	CondTxtNight         string   `protobuf:"bytes,813,opt,name=condTxtNight,proto3" json:"condTxtNight,omitempty"`
	Pm25                 string   `protobuf:"bytes,814,opt,name=pm25,proto3" json:"pm25,omitempty"`
	Pm10                 string   `protobuf:"bytes,815,opt,name=pm10,proto3" json:"pm10,omitempty"`
	Aqi                  string   `protobuf:"bytes,816,opt,name=aqi,proto3" json:"aqi,omitempty"`
	Quality              string   `protobuf:"bytes,817,opt,name=quality,proto3" json:"quality,omitempty"`
	WindDeg              string   `protobuf:"bytes,818,opt,name=windDeg,proto3" json:"windDeg,omitempty"`
	WindDir              string   `protobuf:"bytes,819,opt,name=windDir,proto3" json:"windDir,omitempty"`
	WindSc               string   `protobuf:"bytes,820,opt,name=windSc,proto3" json:"windSc,omitempty"`
	WindSpd              string   `protobuf:"bytes,821,opt,name=windSpd,proto3" json:"windSpd,omitempty"`
	Pres                 string   `protobuf:"bytes,822,opt,name=pres,proto3" json:"pres,omitempty"`
	Vis                  string   `protobuf:"bytes,823,opt,name=vis,proto3" json:"vis,omitempty"`
	Type                 string   `protobuf:"bytes,824,opt,name=type,proto3" json:"type,omitempty"`
	Cold                 string   `protobuf:"bytes,825,opt,name=cold,proto3" json:"cold,omitempty"`
	Notice               string   `protobuf:"bytes,826,opt,name=notice,proto3" json:"notice,omitempty"`
	Source               string   `protobuf:"bytes,827,opt,name=source,proto3" json:"source,omitempty"`
	CreateTime           string   `protobuf:"bytes,828,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherData) Reset()         { *m = WeatherData{} }
func (m *WeatherData) String() string { return proto.CompactTextString(m) }
func (*WeatherData) ProtoMessage()    {}
func (*WeatherData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{3}
}

func (m *WeatherData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherData.Unmarshal(m, b)
}
func (m *WeatherData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherData.Marshal(b, m, deterministic)
}
func (m *WeatherData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherData.Merge(m, src)
}
func (m *WeatherData) XXX_Size() int {
	return xxx_messageInfo_WeatherData.Size(m)
}
func (m *WeatherData) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherData.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherData proto.InternalMessageInfo

func (m *WeatherData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WeatherData) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *WeatherData) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *WeatherData) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *WeatherData) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *WeatherData) GetTem() string {
	if m != nil {
		return m.Tem
	}
	return ""
}

func (m *WeatherData) GetTemHigh() string {
	if m != nil {
		return m.TemHigh
	}
	return ""
}

func (m *WeatherData) GetTemLow() string {
	if m != nil {
		return m.TemLow
	}
	return ""
}

func (m *WeatherData) GetCondCodeDay() string {
	if m != nil {
		return m.CondCodeDay
	}
	return ""
}

func (m *WeatherData) GetCondTxtDay() string {
	if m != nil {
		return m.CondTxtDay
	}
	return ""
}

func (m *WeatherData) GetCondCodeNight() string {
	if m != nil {
		return m.CondCodeNight
	}
	return ""
}

func (m *WeatherData) GetCondTxtNight() string {
	if m != nil {
		return m.CondTxtNight
	}
	return ""
}

func (m *WeatherData) GetPm25() string {
	if m != nil {
		return m.Pm25
	}
	return ""
}

func (m *WeatherData) GetPm10() string {
	if m != nil {
		return m.Pm10
	}
	return ""
}

func (m *WeatherData) GetAqi() string {
	if m != nil {
		return m.Aqi
	}
	return ""
}

func (m *WeatherData) GetQuality() string {
	if m != nil {
		return m.Quality
	}
	return ""
}

func (m *WeatherData) GetWindDeg() string {
	if m != nil {
		return m.WindDeg
	}
	return ""
}

func (m *WeatherData) GetWindDir() string {
	if m != nil {
		return m.WindDir
	}
	return ""
}

func (m *WeatherData) GetWindSc() string {
	if m != nil {
		return m.WindSc
	}
	return ""
}

func (m *WeatherData) GetWindSpd() string {
	if m != nil {
		return m.WindSpd
	}
	return ""
}

func (m *WeatherData) GetPres() string {
	if m != nil {
		return m.Pres
	}
	return ""
}

func (m *WeatherData) GetVis() string {
	if m != nil {
		return m.Vis
	}
	return ""
}

func (m *WeatherData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WeatherData) GetCold() string {
	if m != nil {
		return m.Cold
	}
	return ""
}

func (m *WeatherData) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *WeatherData) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *WeatherData) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

//当前近海天气的数据
type SeasData struct {
	CityCode             string           `protobuf:"bytes,1,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	City                 string           `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	UpdateTime           string           `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Data                 *SeasWeatherData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SeasData) Reset()         { *m = SeasData{} }
func (m *SeasData) String() string { return proto.CompactTextString(m) }
func (*SeasData) ProtoMessage()    {}
func (*SeasData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{4}
}

func (m *SeasData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasData.Unmarshal(m, b)
}
func (m *SeasData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasData.Marshal(b, m, deterministic)
}
func (m *SeasData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasData.Merge(m, src)
}
func (m *SeasData) XXX_Size() int {
	return xxx_messageInfo_SeasData.Size(m)
}
func (m *SeasData) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasData.DiscardUnknown(m)
}

var xxx_messageInfo_SeasData proto.InternalMessageInfo

func (m *SeasData) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *SeasData) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SeasData) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *SeasData) GetData() *SeasWeatherData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SeasWeatherData struct {
	PortName             string           `protobuf:"bytes,1,opt,name=portName,proto3" json:"portName,omitempty"`
	SeaLevel             string           `protobuf:"bytes,2,opt,name=seaLevel,proto3" json:"seaLevel,omitempty"`
	Date                 string           `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Tide                 []string         `protobuf:"bytes,4,rep,name=tide,proto3" json:"tide,omitempty"`
	Range                []*SeasRangeData `protobuf:"bytes,5,rep,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SeasWeatherData) Reset()         { *m = SeasWeatherData{} }
func (m *SeasWeatherData) String() string { return proto.CompactTextString(m) }
func (*SeasWeatherData) ProtoMessage()    {}
func (*SeasWeatherData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{5}
}

func (m *SeasWeatherData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasWeatherData.Unmarshal(m, b)
}
func (m *SeasWeatherData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasWeatherData.Marshal(b, m, deterministic)
}
func (m *SeasWeatherData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasWeatherData.Merge(m, src)
}
func (m *SeasWeatherData) XXX_Size() int {
	return xxx_messageInfo_SeasWeatherData.Size(m)
}
func (m *SeasWeatherData) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasWeatherData.DiscardUnknown(m)
}

var xxx_messageInfo_SeasWeatherData proto.InternalMessageInfo

func (m *SeasWeatherData) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func (m *SeasWeatherData) GetSeaLevel() string {
	if m != nil {
		return m.SeaLevel
	}
	return ""
}

func (m *SeasWeatherData) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *SeasWeatherData) GetTide() []string {
	if m != nil {
		return m.Tide
	}
	return nil
}

func (m *SeasWeatherData) GetRange() []*SeasRangeData {
	if m != nil {
		return m.Range
	}
	return nil
}

type SeasRangeData struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Height               string   `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeasRangeData) Reset()         { *m = SeasRangeData{} }
func (m *SeasRangeData) String() string { return proto.CompactTextString(m) }
func (*SeasRangeData) ProtoMessage()    {}
func (*SeasRangeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb1c2905324e013, []int{6}
}

func (m *SeasRangeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasRangeData.Unmarshal(m, b)
}
func (m *SeasRangeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasRangeData.Marshal(b, m, deterministic)
}
func (m *SeasRangeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasRangeData.Merge(m, src)
}
func (m *SeasRangeData) XXX_Size() int {
	return xxx_messageInfo_SeasRangeData.Size(m)
}
func (m *SeasRangeData) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasRangeData.DiscardUnknown(m)
}

var xxx_messageInfo_SeasRangeData proto.InternalMessageInfo

func (m *SeasRangeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SeasRangeData) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *SeasRangeData) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func init() {
	proto.RegisterType((*DataReq)(nil), "pb.DataReq")
	proto.RegisterType((*ForecastData)(nil), "pb.ForecastData")
	proto.RegisterType((*NowData)(nil), "pb.NowData")
	proto.RegisterType((*WeatherData)(nil), "pb.WeatherData")
	proto.RegisterType((*SeasData)(nil), "pb.SeasData")
	proto.RegisterType((*SeasWeatherData)(nil), "pb.SeasWeatherData")
	proto.RegisterType((*SeasRangeData)(nil), "pb.SeasRangeData")
}

func init() { proto.RegisterFile("weather.ext.proto", fileDescriptor_1cb1c2905324e013) }

var fileDescriptor_1cb1c2905324e013 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4b, 0x4f, 0x1b, 0x3b,
	0x14, 0x66, 0x92, 0x30, 0x80, 0x03, 0x97, 0x8b, 0x91, 0xee, 0x3d, 0x97, 0x5b, 0xb5, 0x10, 0x54,
	0x15, 0xa9, 0x52, 0x04, 0x54, 0xfd, 0x05, 0x45, 0x55, 0x17, 0x28, 0x95, 0x08, 0x12, 0x6b, 0x33,
	0x73, 0x94, 0x58, 0xca, 0xc4, 0x13, 0x8f, 0x49, 0x60, 0xd3, 0x4d, 0xd5, 0x3f, 0xd1, 0x5d, 0xdf,
	0xad, 0xfa, 0x7e, 0x3f, 0x97, 0xfd, 0x61, 0xd5, 0xb1, 0x3d, 0x61, 0x06, 0xc4, 0x92, 0x9d, 0xbf,
	0xef, 0x3b, 0xe3, 0xf3, 0xf9, 0xd8, 0xe7, 0x0c, 0x5b, 0x18, 0xa1, 0x30, 0x5d, 0xd4, 0x4d, 0x3c,
	0x34, 0xcd, 0x54, 0x2b, 0xa3, 0x78, 0x25, 0xdd, 0x6f, 0xec, 0xb1, 0xa9, 0x2d, 0x61, 0xc4, 0x0e,
	0x0e, 0xf8, 0x05, 0x36, 0x23, 0xd2, 0xb4, 0x8d, 0x91, 0x46, 0x03, 0x6a, 0x39, 0x58, 0x9b, 0xd9,
	0x39, 0x26, 0xf8, 0x12, 0x9b, 0x8e, 0xa4, 0x39, 0xba, 0xa1, 0x62, 0x84, 0xd4, 0x8a, 0x63, 0xcc,
	0x39, 0xab, 0xd1, 0x1a, 0x06, 0x96, 0xb7, 0xeb, 0xc6, 0xdd, 0x80, 0xcd, 0xde, 0x54, 0x1a, 0x23,
	0x91, 0x19, 0xca, 0x50, 0xda, 0x20, 0x38, 0x63, 0x83, 0xca, 0xf1, 0x06, 0xfc, 0x22, 0x63, 0x07,
	0x69, 0x2c, 0x0c, 0xee, 0xca, 0x04, 0xa1, 0x6a, 0x95, 0x02, 0xc3, 0x57, 0x59, 0x2d, 0x16, 0x46,
	0x40, 0x6d, 0xb9, 0xba, 0x56, 0xdf, 0x9c, 0x6f, 0xa6, 0xfb, 0xcd, 0x3d, 0x77, 0x44, 0x7b, 0x20,
	0x2b, 0x36, 0xee, 0xb0, 0xa9, 0x96, 0x1a, 0x9d, 0x73, 0xfe, 0xe0, 0xec, 0xfc, 0xbf, 0x27, 0x59,
	0xbd, 0xc0, 0xf2, 0x79, 0x56, 0x91, 0x31, 0x3c, 0x08, 0xed, 0x6e, 0x15, 0x19, 0xf3, 0xff, 0x0b,
	0xae, 0x1e, 0x86, 0x27, 0x6c, 0x2d, 0x7a, 0x5b, 0x8f, 0xc2, 0x82, 0xaf, 0x45, 0x9b, 0x17, 0xe1,
	0xb1, 0x27, 0x09, 0xf0, 0x4b, 0x25, 0xb3, 0x4f, 0xc2, 0x53, 0x6e, 0x17, 0x58, 0xd5, 0x60, 0x02,
	0x4f, 0x9d, 0x42, 0x6b, 0xfe, 0x1f, 0x9b, 0x32, 0x98, 0xdc, 0x92, 0x9d, 0x2e, 0x3c, 0x73, 0x74,
	0x8e, 0xf9, 0xbf, 0x2c, 0x34, 0x98, 0x6c, 0xab, 0x11, 0x3c, 0x77, 0x8a, 0x87, 0x7c, 0x85, 0xd5,
	0x23, 0xd5, 0x8f, 0xc9, 0xdd, 0x96, 0x38, 0x82, 0x17, 0x4e, 0x2d, 0x72, 0x64, 0x85, 0xe0, 0xee,
	0xa1, 0xa1, 0x88, 0x97, 0xde, 0xca, 0x31, 0xc5, 0x2f, 0xb3, 0xb9, 0x3c, 0xbe, 0x25, 0x3b, 0x5d,
	0x03, 0xaf, 0x5c, 0x4c, 0x99, 0xe5, 0xab, 0x6c, 0xd6, 0x7f, 0xe4, 0xa2, 0x5e, 0xbb, 0xa8, 0x12,
	0x49, 0xc5, 0x48, 0x93, 0xcd, 0xeb, 0xf0, 0xc6, 0x17, 0x83, 0x80, 0x23, 0x37, 0xd6, 0xe1, 0xed,
	0x98, 0xdc, 0x58, 0xa7, 0x02, 0x88, 0x81, 0x84, 0x77, 0xbe, 0x00, 0x62, 0x20, 0xa9, 0x00, 0x83,
	0x03, 0xd1, 0xa3, 0x0a, 0xbf, 0xf7, 0x05, 0xf0, 0x98, 0xa4, 0x91, 0xec, 0xc7, 0x5b, 0xd8, 0x81,
	0x0f, 0x5e, 0xf2, 0x78, 0x2c, 0x49, 0x0d, 0x1f, 0x8b, 0x92, 0xd4, 0x54, 0x36, 0x5a, 0xb6, 0x23,
	0xf8, 0xe4, 0xcb, 0xe6, 0x60, 0xfe, 0x4d, 0x3b, 0x8d, 0xe1, 0x73, 0xe1, 0x9b, 0x76, 0x1a, 0x5b,
	0xb3, 0x1a, 0x33, 0xf8, 0x92, 0x9b, 0xd5, 0x98, 0x91, 0xd9, 0xa1, 0xcc, 0xe0, 0xab, 0x37, 0x3b,
	0x94, 0x19, 0xc5, 0x99, 0xa3, 0x14, 0xe1, 0x9b, 0x8f, 0x23, 0x60, 0x1f, 0x88, 0xea, 0xc5, 0xf0,
	0x3d, 0x7f, 0x20, 0xaa, 0x17, 0x93, 0x8b, 0xbe, 0x32, 0x32, 0x42, 0xf8, 0xe1, 0x5d, 0x38, 0x48,
	0x42, 0xa6, 0x0e, 0x74, 0x84, 0xf0, 0xd3, 0x0b, 0x0e, 0xda, 0x2b, 0xd3, 0x98, 0xbf, 0x9e, 0x5f,
	0xf9, 0x95, 0x8d, 0x29, 0x6a, 0xe6, 0xe9, 0x36, 0x8a, 0xec, 0x5c, 0x1a, 0xe9, 0x4a, 0xa9, 0x91,
	0x16, 0xa9, 0x91, 0x28, 0xd7, 0xe9, 0x66, 0xba, 0x1f, 0xb0, 0xf9, 0x13, 0x0a, 0x99, 0x49, 0x95,
	0x36, 0x2d, 0x91, 0x8c, 0xcd, 0xe4, 0x98, 0xb4, 0x0c, 0xc5, 0x36, 0x0e, 0xb1, 0xe7, 0x0d, 0x8d,
	0x31, 0x19, 0xb5, 0x5d, 0x54, 0x2d, 0x34, 0x11, 0x67, 0x35, 0x23, 0x63, 0xb4, 0x13, 0x85, 0x2a,
	0x2c, 0x63, 0x32, 0x37, 0xa9, 0x45, 0xbf, 0x83, 0x30, 0x69, 0xc7, 0xcc, 0x42, 0xee, 0x6e, 0x87,
	0x48, 0xeb, 0xcd, 0xe9, 0x8d, 0xdb, 0x6c, 0xae, 0xc4, 0xdb, 0xdd, 0xe8, 0xc2, 0x82, 0xc2, 0x7d,
	0xd9, 0x0c, 0x09, 0xe6, 0xe5, 0xa1, 0x35, 0xff, 0x87, 0x85, 0x5d, 0xb4, 0x2f, 0xdc, 0x79, 0xf1,
	0x68, 0xf3, 0x5e, 0xc0, 0xfe, 0xf2, 0x27, 0x6d, 0xa3, 0x1e, 0xd2, 0x05, 0xae, 0xb0, 0x6a, 0x4b,
	0x8d, 0x78, 0x9d, 0x4c, 0xf8, 0xa9, 0xbd, 0x64, 0x81, 0x9f, 0x71, 0x8d, 0x09, 0x7e, 0x95, 0x4d,
	0xe7, 0x53, 0xb7, 0x1c, 0xf7, 0x37, 0x81, 0xe2, 0x40, 0x6e, 0x4c, 0xd0, 0x08, 0x23, 0xcf, 0xe5,
	0xc0, 0xd9, 0xfc, 0x88, 0x2e, 0x68, 0x3f, 0xb4, 0x3f, 0x8b, 0x6b, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x12, 0xda, 0x22, 0xec, 0x41, 0x06, 0x00, 0x00,
}
